import { IComment, ITelNumberLine } from '../types';

export const dataComments: IComment[] = [
  {
    username: 'Анна',
    date: '23.09.2023',
    time: '17:47',
    telNumber: '3852631066',
    viewsCount: 4,
    commentsCount: 1,
    description:
      'Не знаю позвонили и попросили паспортные данные представились сотрудниками компании Теле2,якобы каждый год надо подтверждать данные,м месяца три назад подтверждали в офисе теле 2.послала на хутур бабочек ловить.',
    category: 'Опросы',
  },
  {
    username: 'Елена',
    date: '23.09.2023',
    time: '17:42',
    telNumber: '9031305821',
    viewsCount: 129,
    commentsCount: 3,
    description: 'Воры мошенники бандиты......',
    category: null,
  },
  {
    username: 'Лина',
    date: '23.09.2023',
    time: '17:38',
    telNumber: '9859975727',
    viewsCount: 207,
    commentsCount: 2,
    description: 'Положительный звонок, сервисное обслуживание',
    category: null,
  },
  {
    username: 'Анна',
    date: '23.09.2023',
    time: '17:47',
    telNumber: '3852631066',
    viewsCount: 4,
    commentsCount: 1,
    description:
      'Не знаю позвонили и попросили паспортные данные представились сотрудниками компании Теле2,якобы каждый год надо подтверждать данные,м месяца три назад подтверждали в офисе теле 2.послала на хутур бабочек ловить.',
    category: 'Опросы',
  },
  {
    username: 'Елена',
    date: '23.09.2023',
    time: '17:42',
    telNumber: '9031305821',
    viewsCount: 129,
    commentsCount: 3,
    description: 'Воры мошенники бандиты......',
    category: null,
  },
  {
    username: 'Лина',
    date: '23.09.2023',
    time: '17:38',
    telNumber: '9859975727',
    viewsCount: 207,
    commentsCount: 2,
    description: 'Положительный звонок, сервисное обслуживание',
    category: null,
  },
  {
    username: 'Анна',
    date: '23.09.2023',
    time: '17:47',
    telNumber: '3852631066',
    viewsCount: 4,
    commentsCount: 1,
    description:
      'Не знаю позвонили и попросили паспортные данные представились сотрудниками компании Теле2,якобы каждый год надо подтверждать данные,м месяца три назад подтверждали в офисе теле 2.послала на хутур бабочек ловить.',
    category: 'Опросы',
  },
  {
    username: 'Елена',
    date: '23.09.2023',
    time: '17:42',
    telNumber: '9031305821',
    viewsCount: 129,
    commentsCount: 3,
    description: 'Воры мошенники бандиты......',
    category: null,
  },
  {
    username: 'Лина',
    date: '23.09.2023',
    time: '17:38',
    telNumber: '9859975727',
    viewsCount: 207,
    commentsCount: 2,
    description: 'Положительный звонок, сервисное обслуживание',
    category: null,
  },
  {
    username: 'Лина',
    date: '23.09.2023',
    time: '17:38',
    telNumber: '9859975727',
    viewsCount: 207,
    commentsCount: 2,
    description: 'Положительный звонок, сервисное обслуживание',
    category: null,
  },
];

export const lastCheckedNumbers: ITelNumberLine[] = [
  {
    telNumber: '9587137815',
    viewsCount: 22,
    commentsCount: 10,
  },
  {
    telNumber: '9956623224',
    viewsCount: 2,
    commentsCount: 3,
  },
  {
    telNumber: '9209466521',
    viewsCount: 5,
    commentsCount: 1,
  },
];
